name: Release

on:
  workflow_dispatch: # manual trigger
  push:

concurrency: scan

jobs:
  build-image:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    env:
      IMAGE: tapad/looker-pd-action
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        uses: docker/build-push-action@v3
        with:
          push: false
          load: true
          tags: ${{ env.IMAGE }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
  
      - name: Scan image
        uses: Tapad/gha-container-scanner@1.0.0
        with: 
          container: ${{ env.IMAGE }}:latest
          wiz_key_id: ${{ secrets.WIZ_KEY_ID }}
          wiz_key_secret: ${{ secrets.WIZ_KEY_SECRET }}
